
INSERT INTO `LONG_SETTING` (REF_CD, VALUE, MODIFIED_TS, `GROUP`, DESCRIPTION, VALUE_TYPE)
VALUES ('SOUTH', 430, '2021-04-21 21:27:38', 'Kúrenie',
        'Juh', null);

INSERT INTO `LONG_SETTING`   (REF_CD, VALUE, MODIFIED_TS, `GROUP`, DESCRIPTION, VALUE_TYPE)
VALUES ('EAST', 690, '2021-04-21 21:28:53', 'Kúrenie',
        'Východ', null);

INSERT INTO `LONG_SETTING` (REF_CD, VALUE, MODIFIED_TS, `GROUP`, DESCRIPTION, VALUE_TYPE)
VALUES ('NORTH', 0, '2021-04-21 21:27:38', 'Kúrenie',
        'Sever', null);

INSERT INTO `LONG_SETTING`   (REF_CD, VALUE, MODIFIED_TS, `GROUP`, DESCRIPTION, VALUE_TYPE)
VALUES ('WEST', 0, '2021-04-21 21:28:53', 'Kúrenie',
        'Západ', null);

INSERT INTO `DOUBLE_SETTING`   (REF_CD, VALUE, MODIFIED_TS, `GROUP`, DESCRIPTION, VALUE_TYPE)
VALUES ('T1_SOLAR_THRESHOLD', 90, '2021-04-21 21:28:53', 'Kúrenie',
        'T1 Hraničná teplota', null);
INSERT INTO `DOUBLE_SETTING`   (REF_CD, VALUE, MODIFIED_TS, `GROUP`, DESCRIPTION, VALUE_TYPE)
VALUES ('T2_WATER_THRESHOLD', 90, '2021-04-21 21:28:53', 'Kúrenie',
        'T2 Hraničná teplota', null);

INSERT INTO `STRING_SETTING` (REF_CD, VALUE, MODIFIED_TS, `GROUP`, DESCRIPTION, VALUE_TYPE)
VALUES ('T1_MEASURE_PLACE', 'SOLAR', '2021-01-18 09:33:38', 'Kúrenie',
        'Meracie miesto pre teplotu T1 obehového čerpadla kolektorov', 'string');

INSERT INTO `STRING_SETTING` (REF_CD, VALUE, MODIFIED_TS, `GROUP`, DESCRIPTION, VALUE_TYPE)
VALUES ('T2_MEASURE_PLACE', 'TA3', '2021-04-19 15:09:31', 'Kúrenie',
        'Meracie miesto pre teplotu T2 obehového čerpadla kolektorov', 'string');

INSERT INTO `STRING_SETTING` (REF_CD, VALUE, MODIFIED_TS, `GROUP`, DESCRIPTION, VALUE_TYPE)
VALUES ('T31_MEASURE_PLACE', 'PRED_TA3', '2021-04-19 15:09:31', 'Kúrenie',
        'Meracie miesto pre teplotu T31', 'string');


UPDATE `LONG_SETTING` SET VALUE = 600 WHERE REF_CD LIKE 'LIGHT_THRESHOLD';

ALTER table `STRING_SETTING` MODIFY VALUE TEXT;
INSERT INTO `STRING_SETTING` (REF_CD, VALUE, MODIFIED_TS, `GROUP`, DESCRIPTION, VALUE_TYPE)
VALUES ('SOLAR_TODAYS_SCHEDULE', null, '2021-04-19 15:09:31', 'Kúrenie',
        'Dnešné natáčanie', 'string');
INSERT INTO `STRING_SETTING` (REF_CD, VALUE, MODIFIED_TS, `GROUP`, DESCRIPTION, VALUE_TYPE)
VALUES ('SOLAR_CURRENT_EVENTS', null, '2021-04-19 15:09:31', 'Kúrenie',
        'Dnešné natáčanie', 'string');
INSERT INTO `STRING_SETTING` (REF_CD, VALUE, MODIFIED_TS, `GROUP`, DESCRIPTION, VALUE_TYPE)
VALUES ('SOLAR_AFTERNOON_TIME', '13:10', '2021-04-19 15:09:31', 'Kúrenie',
        'Dnešné natáčanie', 'string')
