UPDATE `DOUBLE_SETTING` t
SET t.VALUE_TYPE = 'number'
WHERE t.REF_CD LIKE 'T1#_SOLAR#_THRESHOLD' ESCAPE '#';

UPDATE `DOUBLE_SETTING` t
SET t.VALUE_TYPE = 'number'
WHERE t.REF_CD LIKE 'T2#_WATER#_THRESHOLD' ESCAPE '#';

INSERT INTO `DOUBLE_SETTING` (REF_CD, VALUE, MODIFIED_TS, `GROUP`, DESCRIPTION, VALUE_TYPE)
VALUES ('T1_T2_DIFF_TEMP', 30, '2021-04-21 21:28:53', 'Kúrenie',
        'Rozdiel teplôt T1 a T2 pri ktorej sa má považovať čerpadlo za nefunkčné', 'number');

INSERT INTO `DOUBLE_SETTING` (REF_CD, VALUE, MODIFIED_TS, `GROUP`, DESCRIPTION, VALUE_TYPE)
VALUES ('T2_WARM_WATER_TEMP', 45, '2021-04-21 21:28:53', 'Kúrenie', 'Teplota kedy je dostatočne teplá voda', 'number');

